-- V12: tenant branding + invoice-legal/payment fields + quick-add descriptions (Phase 14A, issue #74)

-- ============================================================
-- 1. BUSINESS TENANT FIELDS
-- ============================================================
-- Branding (logo_path, accent_colour) is the only data exposed by the public lookup
-- (GET /api/v1/public/businesses/{slug}). The invoice-legal / bank / payment fields are
-- PRIVATE (authenticated-only, Phase 14C) and must never be returned by the public endpoint.
--
-- All branding/legal/payment columns are NULLABLE: V4 already seeds business rows, so a
-- NOT NULL column without a DEFAULT would fail on a fresh DB / prod apply. Only
-- invoice_template_key is NOT NULL, and only because it carries DEFAULT 'standard'.

ALTER TABLE business ADD COLUMN logo_path               VARCHAR(500);
ALTER TABLE business ADD COLUMN accent_colour           VARCHAR(20);
ALTER TABLE business ADD COLUMN abn                     VARCHAR(20);
ALTER TABLE business ADD COLUMN bank_name               VARCHAR(150);
ALTER TABLE business ADD COLUMN bsb                     VARCHAR(10);
ALTER TABLE business ADD COLUMN account_number          VARCHAR(30);
ALTER TABLE business ADD COLUMN account_name            VARCHAR(150);
ALTER TABLE business ADD COLUMN terms_and_conditions    TEXT;
ALTER TABLE business ADD COLUMN stripe_payment_link_url VARCHAR(500);
ALTER TABLE business ADD COLUMN invoice_template_key    VARCHAR(50) NOT NULL DEFAULT 'standard';


-- ============================================================
-- 2. QUICK-ADD DESCRIPTIONS
-- ============================================================
-- Per-business reusable "details of sale" quick-add lines (wired into the frontend in a
-- later phase). The text column is named `description` on purpose: `text` is a Postgres
-- type-name keyword and would be a locked-in footgun once shipped.

CREATE TABLE business_quick_description (
    business_quick_description_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id                    BIGINT    NOT NULL,
    description                    TEXT      NOT NULL,
    sort_order                     INTEGER   NOT NULL DEFAULT 0,
    created_at                     TIMESTAMP NOT NULL DEFAULT now(),
    updated_at                     TIMESTAMP NOT NULL DEFAULT now()
);

ALTER TABLE business_quick_description
    ADD CONSTRAINT fk_business_quick_description_business
    FOREIGN KEY (business_id) REFERENCES business (business_id);

ALTER TABLE business_quick_description
    ADD CONSTRAINT chk_bqd_description_not_blank
    CHECK (trim(description) <> '');

CREATE INDEX idx_business_quick_description_business
    ON business_quick_description (business_id);
