-- V15: lead enquiry form (Phase 15F)
-- One-per-order job/order enquiry captured inside the Customer tab. This is order-specific
-- enquiry data, NOT generic customer identity — it lives in its own table and is NOT stored on
-- order_customer and does NOT widen sales_order. Mirrors the order_customer one-to-one shape:
-- BIGINT IDENTITY PK, order_id FK to sales_order(order_id), UNIQUE (order_id) so the application
-- INSERT ... ON CONFLICT (order_id) DO UPDATE upsert can never create a second row.
--
--   lead_type                    how the lead came in: FLOOR / PHONE / INTERNET, or NULL = unanswered.
--                                Single choice (chk_order_enquiry_lead_type backstops the app-level
--                                validation in OrderService — exact-case values only).
--   carpet / hard_floor          the products the customer is looking for. Independent booleans
--                                (both or neither may be true) and deliberately decoupled from
--                                sales_order.flooring_type (SOFT/HARD) — never auto-filled from it.
--   subfloor_concrete/timber/tile  independent multi-select booleans (any combination, incl. none).
--                                Intentionally three booleans, NOT one enum / one radio group.
--   fully_installed / uplift /   tri-state Yes / No / unanswered: nullable BOOLEAN with NO default.
--   furniture / stairs           true = Yes, false = No, NULL = unanswered. The application binds a
--                                boxed Boolean and never coerces NULL to false for these four.
--   the 9 TEXT columns           free-form narrative, no length cap (same as plan_numbers /
--                                details_of_sale / note_text); blank-after-trim is stored as NULL.
--
-- No ON DELETE clause (matches every other child-of-order FK in V3 — default RESTRICT). No CHECK
-- restricting subfloor to a single option.

CREATE TABLE order_enquiry (
    order_enquiry_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id                     BIGINT       NOT NULL,
    lead_type                    VARCHAR(20),
    carpet                       BOOLEAN   NOT NULL DEFAULT FALSE,
    hard_floor                   BOOLEAN   NOT NULL DEFAULT FALSE,
    product_fit_timing           TEXT,
    product_usage_context        TEXT,
    rooms_to_cover               TEXT,
    textured_or_plain            TEXT,
    light_or_dark_tones          TEXT,
    colours_interested           TEXT,
    current_flooring_and_reason  TEXT,
    products_discussed           TEXT,
    fully_installed              BOOLEAN,
    uplift                       BOOLEAN,
    furniture                    BOOLEAN,
    stairs                       BOOLEAN,
    subfloor_concrete            BOOLEAN   NOT NULL DEFAULT FALSE,
    subfloor_timber              BOOLEAN   NOT NULL DEFAULT FALSE,
    subfloor_tile                BOOLEAN   NOT NULL DEFAULT FALSE,
    brief_summary                TEXT,
    created_at                   TIMESTAMP NOT NULL DEFAULT now(),
    updated_at                   TIMESTAMP NOT NULL DEFAULT now()
);

-- One enquiry record per order (the upsert's ON CONFLICT target). PostgreSQL auto-indexes the
-- UNIQUE constraint, so no separate index on order_id is needed (same as order_customer in V3).
ALTER TABLE order_enquiry
    ADD CONSTRAINT uq_order_enquiry_order UNIQUE (order_id);

ALTER TABLE order_enquiry
    ADD CONSTRAINT fk_order_enquiry_order
    FOREIGN KEY (order_id) REFERENCES sales_order (order_id);

-- lead_type is a single choice or NULL. App-level validation in OrderService is the
-- primary path (returns 400 VALIDATION_FAILED on an invalid value); this CHECK is the backstop.
ALTER TABLE order_enquiry
    ADD CONSTRAINT chk_order_enquiry_lead_type
    CHECK (lead_type IS NULL OR lead_type IN ('FLOOR', 'PHONE', 'INTERNET'));
