-- V16: quotation tables (Phase 16B contract §4 / Phase 16C build)
--
-- Five new tables for the quotation feature. Phase 16C PR1 (this work) uses ONLY the two draft
-- tables (quote_draft, quote_draft_line). The append-only issued layer (quote_version,
-- quote_version_line) and the public-link tokens (quote_token) are created here as schema-only
-- so the whole feature lives in one migration (contract §4 / §13: "five new tables under V16");
-- they gain behaviour in Phase 16E (delivery) / 16F (remote acceptance + conversion).
--
-- Conventions follow V2/V14/V15: BIGINT IDENTITY PK, snake_case, money DECIMAL(10,2) (BigDecimal
-- scale 2 HALF_UP), created_at/updated_at TIMESTAMP NOT NULL DEFAULT now(); named uq_/fk_/chk_/idx_
-- constraints via ALTER TABLE / CREATE INDEX; NO ON DELETE on FKs (default RESTRICT, as every
-- child-of-order FK in V3) EXCEPT the two owned _line -> parent FKs which CASCADE (contract §4.2/§4.4).
-- Categoricals are VARCHAR + CHECK (the V15 lead_type precedent), NOT new Postgres enum types.
--
-- Migration policy: V1-V15 stay locked; this is a NEW migration. The CI "Locked migration
-- protection" guard currently covers V1-V13 only, so V14/V15/V16 are outside it until the Phase 17
-- schema-only squash collapses everything into one baseline and re-locks CI.

-- ============================================================
-- quote_draft  [USED IN PR1] — editable working draft, one per order
-- ============================================================
CREATE TABLE quote_draft (
    quote_draft_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id              BIGINT        NOT NULL,
    itemised              BOOLEAN       NOT NULL DEFAULT TRUE,
    quote_total_ex_gst    DECIMAL(10,2) NOT NULL,
    quote_total_inc_gst   DECIMAL(10,2) NOT NULL,
    created_at            TIMESTAMP     NOT NULL DEFAULT now(),
    updated_at            TIMESTAMP     NOT NULL DEFAULT now()
);

-- One draft per order (the INSERT ... ON CONFLICT (order_id) DO UPDATE upsert target; Postgres
-- auto-indexes the UNIQUE, so no separate index on order_id — same as order_enquiry in V15).
ALTER TABLE quote_draft
    ADD CONSTRAINT uq_quote_draft_order UNIQUE (order_id);

-- No ON DELETE clause (matches every other child-of-order FK in V3 — default RESTRICT).
ALTER TABLE quote_draft
    ADD CONSTRAINT fk_quote_draft_order
    FOREIGN KEY (order_id) REFERENCES sales_order (order_id);

-- ============================================================
-- quote_draft_line  [USED IN PR1] — customer-facing draft lines
-- ============================================================
-- No cost column: quote lines are customer-facing only; costs live on the order's product/charge
-- lines and are never copied here or exposed (contract §4.2). line_type is ITEM or ADJUSTMENT:
-- ITEM lines carry quantity + unit_price_ex_gst (line_total = qty * unit, server-checked);
-- ADJUSTMENT lines carry a signed line_total_ex_gst (may be negative) and NULL quantity/unit.
CREATE TABLE quote_draft_line (
    quote_draft_line_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quote_draft_id        BIGINT        NOT NULL,
    line_type             VARCHAR(16)   NOT NULL,
    description           VARCHAR(500)  NOT NULL,
    quantity              DECIMAL(10,2),
    unit_price_ex_gst     DECIMAL(10,2),
    line_total_ex_gst     DECIMAL(10,2) NOT NULL,
    sort_order            INTEGER       NOT NULL
);

-- Owned child: cascade when the parent draft is deleted (contract §4.2).
ALTER TABLE quote_draft_line
    ADD CONSTRAINT fk_quote_draft_line_draft
    FOREIGN KEY (quote_draft_id) REFERENCES quote_draft (quote_draft_id) ON DELETE CASCADE;

-- App validates line_type before this DB backstop (returns 400 VALIDATION_FAILED on a bad value).
ALTER TABLE quote_draft_line
    ADD CONSTRAINT chk_quote_draft_line_type
    CHECK (line_type IN ('ITEM', 'ADJUSTMENT'));

-- DB backstop for the ITEM/ADJUSTMENT shape the application enforces first:
--   ITEM       -> quantity + unit_price_ex_gst present
--   ADJUSTMENT -> quantity + unit_price_ex_gst NULL (signed line_total only)
ALTER TABLE quote_draft_line
    ADD CONSTRAINT chk_quote_draft_line_shape
    CHECK (
        (line_type = 'ITEM' AND quantity IS NOT NULL AND unit_price_ex_gst IS NOT NULL)
        OR
        (line_type = 'ADJUSTMENT' AND quantity IS NULL AND unit_price_ex_gst IS NULL)
    );

-- Non-negative display order (app validates first; this is the DB backstop).
ALTER TABLE quote_draft_line
    ADD CONSTRAINT chk_quote_draft_line_sort_order_non_negative
    CHECK (sort_order >= 0);

CREATE INDEX idx_quote_draft_line_draft ON quote_draft_line (quote_draft_id);

-- ============================================================
-- quote_version  [SCHEMA ONLY — Phase 16E/16F] — append-only issued snapshots
-- ============================================================
CREATE TABLE quote_version (
    quote_version_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id                    BIGINT        NOT NULL,
    version_number              INTEGER       NOT NULL,
    status                      VARCHAR(16)   NOT NULL,
    itemised                    BOOLEAN       NOT NULL,
    quote_total_ex_gst          DECIMAL(10,2) NOT NULL,
    quote_total_inc_gst         DECIMAL(10,2) NOT NULL,
    flooring_type_snapshot      VARCHAR(8)    NOT NULL,
    terms_snapshot              TEXT,
    details_of_sale_snapshot    TEXT,
    sent_channel                VARCHAR(8),
    first_sent_at               TIMESTAMP,
    last_sent_at                TIMESTAMP,
    last_emailed_at             TIMESTAMP,
    viewed_at                   TIMESTAMP,
    accepted_at                 TIMESTAMP,
    accepted_customer_name      VARCHAR(150),
    accepted_signature_file_id  BIGINT,
    issued_pdf_file_id          BIGINT,
    signed_pdf_file_id          BIGINT,
    created_by_user_id          BIGINT        NOT NULL,
    created_at                  TIMESTAMP     NOT NULL DEFAULT now()
);

-- order_id / created_by_user_id FKs: no ON DELETE (default RESTRICT), matching V3 convention.
ALTER TABLE quote_version
    ADD CONSTRAINT fk_quote_version_order
    FOREIGN KEY (order_id) REFERENCES sales_order (order_id);

ALTER TABLE quote_version
    ADD CONSTRAINT fk_quote_version_created_by
    FOREIGN KEY (created_by_user_id) REFERENCES app_user (user_id);

-- Signature/PDF references reuse stored_file. accepted_signature_file_id is NOT unique (a carried-
-- forward signature may be referenced by more than one row); the two PDF ids ARE unique (contract
-- §4.3). UNIQUE on a nullable column is fine — Postgres permits multiple NULLs.
ALTER TABLE quote_version
    ADD CONSTRAINT fk_quote_version_accepted_sig
    FOREIGN KEY (accepted_signature_file_id) REFERENCES stored_file (stored_file_id);

ALTER TABLE quote_version
    ADD CONSTRAINT fk_quote_version_issued_pdf
    FOREIGN KEY (issued_pdf_file_id) REFERENCES stored_file (stored_file_id);

ALTER TABLE quote_version
    ADD CONSTRAINT uq_quote_version_issued_pdf UNIQUE (issued_pdf_file_id);

ALTER TABLE quote_version
    ADD CONSTRAINT fk_quote_version_signed_pdf
    FOREIGN KEY (signed_pdf_file_id) REFERENCES stored_file (stored_file_id);

ALTER TABLE quote_version
    ADD CONSTRAINT uq_quote_version_signed_pdf UNIQUE (signed_pdf_file_id);

-- DRAFT is the draft layer's conceptual state and is NEVER stored here (contract §4.3).
ALTER TABLE quote_version
    ADD CONSTRAINT chk_quote_version_status
    CHECK (status IN ('ISSUED', 'SUPERSEDED', 'ACCEPTED', 'EXPIRED', 'CANCELLED'));

ALTER TABLE quote_version
    ADD CONSTRAINT chk_quote_version_flooring
    CHECK (flooring_type_snapshot IN ('SOFT', 'HARD'));

ALTER TABLE quote_version
    ADD CONSTRAINT chk_quote_version_channel
    CHECK (sent_channel IS NULL OR sent_channel IN ('EMAIL', 'SMS'));

-- per-order version sequence (invoice append-only precedent: uq_invoice_order_version).
ALTER TABLE quote_version
    ADD CONSTRAINT uq_quote_version_order_version UNIQUE (order_id, version_number);

ALTER TABLE quote_version
    ADD CONSTRAINT chk_quote_version_number_positive CHECK (version_number > 0);

-- At most ONE active issued version per order (contract §4.3 invariant). DB backstop, not an
-- app-only invariant — V16 becomes immutable after commit. A partial unique index counts only
-- ISSUED rows, so SUPERSEDED/ACCEPTED/EXPIRED/CANCELLED rows for the same order stay unconstrained.
CREATE UNIQUE INDEX uq_quote_version_one_issued_per_order
    ON quote_version (order_id)
    WHERE status = 'ISSUED';

-- ============================================================
-- quote_version_line  [SCHEMA ONLY — Phase 16E] — immutable snapshot of issued lines
-- ============================================================
CREATE TABLE quote_version_line (
    quote_version_line_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quote_version_id        BIGINT        NOT NULL,
    line_type               VARCHAR(16)   NOT NULL,
    description             VARCHAR(500)  NOT NULL,
    quantity                DECIMAL(10,2),
    unit_price_ex_gst       DECIMAL(10,2),
    line_total_ex_gst       DECIMAL(10,2) NOT NULL,
    sort_order              INTEGER       NOT NULL
);

ALTER TABLE quote_version_line
    ADD CONSTRAINT fk_quote_version_line_version
    FOREIGN KEY (quote_version_id) REFERENCES quote_version (quote_version_id) ON DELETE CASCADE;

ALTER TABLE quote_version_line
    ADD CONSTRAINT chk_quote_version_line_type
    CHECK (line_type IN ('ITEM', 'ADJUSTMENT'));

-- Same ITEM/ADJUSTMENT shape backstop as quote_draft_line (the snapshot mirrors the draft line).
ALTER TABLE quote_version_line
    ADD CONSTRAINT chk_quote_version_line_shape
    CHECK (
        (line_type = 'ITEM' AND quantity IS NOT NULL AND unit_price_ex_gst IS NOT NULL)
        OR
        (line_type = 'ADJUSTMENT' AND quantity IS NULL AND unit_price_ex_gst IS NULL)
    );

ALTER TABLE quote_version_line
    ADD CONSTRAINT chk_quote_version_line_sort_order_non_negative
    CHECK (sort_order >= 0);

CREATE INDEX idx_quote_version_line_version ON quote_version_line (quote_version_id);

-- ============================================================
-- quote_token  [SCHEMA ONLY — Phase 16E/16F] — public-link tokens (never deleted)
-- ============================================================
-- A token row is never deleted/cleared: dead links keep their row + a status reason so the public
-- GET can resolve the hash and return the correct per-state message (contract §4.5). Only the token
-- HASH is stored. "One ACTIVE token per order / active issued quote" is an application invariant
-- (the token row has no order_id), not a DB partial index. expires_at = created_at + 7d is set by
-- the application, not a SQL default.
CREATE TABLE quote_token (
    quote_token_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quote_version_id    BIGINT        NOT NULL,
    token_hash          VARCHAR(255)  NOT NULL,
    status              VARCHAR(16)   NOT NULL,
    expires_at          TIMESTAMP     NOT NULL,
    created_at          TIMESTAMP     NOT NULL DEFAULT now(),
    dead_at             TIMESTAMP
);

ALTER TABLE quote_token
    ADD CONSTRAINT fk_quote_token_version
    FOREIGN KEY (quote_version_id) REFERENCES quote_version (quote_version_id);

ALTER TABLE quote_token
    ADD CONSTRAINT uq_quote_token_hash UNIQUE (token_hash);

ALTER TABLE quote_token
    ADD CONSTRAINT chk_quote_token_status
    CHECK (status IN ('ACTIVE', 'REPLACED', 'SUPERSEDED', 'EXPIRED', 'CANCELLED', 'CONSUMED'));

CREATE INDEX idx_quote_token_version ON quote_token (quote_version_id);

-- At most ONE live (ACTIVE) token per issued version (contract §8: a resend marks the old token
-- REPLACED and mints a new ACTIVE one). DB backstop, schema-only — no token behaviour in PR1.
-- A partial unique index counts only ACTIVE rows, so REPLACED/SUPERSEDED/EXPIRED/CANCELLED/CONSUMED
-- tokens for the same version stay unconstrained (they are kept for messaging, never deleted).
CREATE UNIQUE INDEX uq_quote_token_one_active_per_version
    ON quote_token (quote_version_id)
    WHERE status = 'ACTIVE';
