package com.flooring.salesportal.order.dto;

/**
 * The {@code data} object for D.10 POST /orders/{orderId}/payments/{paymentTransactionId}/void
 * (Phase 15D). Serializes as
 * {@code { "data": { "payment_transaction": { ...E.3 + void markers... },
 * "payment_summary": { ...E.4... }, "current_invoice": { ...E.1... } },
 * "message": "Payment voided. Current invoice updated." } }.
 *
 * <p>Intentionally the SAME shape as {@link RecordPaymentResponse} so the frontend (PR2) can reuse the
 * payment-mutation handling: {@code payment_transaction} is the now-voided row (its {@code voided_at} /
 * {@code voided_by_name} populated), {@code payment_summary} reflects the recalculated ACTIVE
 * {@code total_paid} / risen {@code balance_due}, and {@code current_invoice} is the new invoice version
 * regenerated by the void. The wrapper is built with {@code ApiResponse.ok(data, message)} and returned
 * 201 Created (the void creates a new current invoice version).
 */
public record VoidPaymentResponse(
        PaymentTransactionReadDto paymentTransaction,
        PaymentSummaryDto paymentSummary,
        CurrentInvoiceSummaryDto currentInvoice
) {
}
