spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/flooring_sales_portal
spring.datasource.username=flooring_user
spring.datasource.password=flooring_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

spring.jackson.property-naming-strategy=SNAKE_CASE

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.sql.init.mode=never

springdoc.swagger-ui.path=/swagger-ui.html